print('**********ESSE PROGRAMA LÊ O CÓD, VALOR E QTD DE UM ITEM E FORNECE O VALOR TOTAL**********')
cod12 = int(input('Por favor, digite o número "12" como código: '))
valor12 = float(input('Digite 5.30 para o valor: '))
qtd12 = int(input('A qtd. é 1, digite o número 1: '))
cod16 = int(input('Por favor, digite o número "16" como código: '))
valor16 = float(input('Digite 5.10 para o valor: '))
qtd16 = int(input('A qtd. é 2, digite o número 2: '))
total = (valor12 * qtd12) + (valor16 * qtd16)
print('O VALOR TOTAL À PAGAR É: R$',total)
print('*******FIM*******')
